repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: check-docstring-first
    -   id: check-merge-conflict
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: local
    hooks:
    -   id: black
        name: black
        stages: [commit]
        language: system
        entry: black
        types: [python]
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: python
        types: [python]
-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: pytest
        language: python
        args: ['./derulo']
        types: [python]
        stages: [push]
